# Site Settings
title: "Zhongxing (Ryan) Zhou - Product Manager & Developer"
description: "UC Berkeley & UMich CS + Business graduate."
permalink: ":title/"
baseurl: ""  # Leave this empty since you're hosting at the root
url: "https://ryanchou24.github.io"  # Your GitHub Pages URL

# Author Information
author: "Ryan Zhou"
author-img: "ryanzhou.JPG"  # Ensure you update this with the correct avatar image path
about-author: "Product Manager and Software Developer focused on Web3 and AI innovations. UC Berkeley & UMich CS + Business graduate."
email: "ryanzhou@berkeley.edu"  # Corrected email domain to ".edu"

# Social Media Links
social:
  twitter: "ryanchou24"
  github: "Ryanchou24"
  linkedin: "zhongxing-zhou"

# SEO and Sitemap Plugins
plugins:
  - jekyll-sitemap   # Auto-generate sitemap for SEO
  - jekyll-seo-tag   # Adds SEO meta tags to your pages
  - jemoji           # Adds emoji support

# Pagination Settings
paginate: 5  # Number of posts per page
paginate_path: "/page/:num"

# Markdown Settings
markdown: kramdown
kramdown:
  input: GFM  # GitHub-Flavored Markdown for more features

# Exclude unnecessary files from build process
exclude:
  - "node_modules"
  - "gulpfile.js"
  - "package.json"
  - "yarn.lock"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
