# title: Hello, world! I'm Ryan Zhou
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# permalink: ':title/'
# baseurl: "" # the base URL of your site
# url: "https://ryanchou24.github.io" # the full URL to your site
# # baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
# # url: "" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# # Author Settings
# author: Ryan Zhou # add your name
# author-img: david-freeman.jpg # add your photo
# about-author: I am a goat focusing on front-end development. Always hungry to keep learning. # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
# social-github: artemsheludko # add your Github handle
# social-linkedin: # add your Linkedin handle
# social-email: # add your Email address

# # Disqus
# discus-identifier: mr-brown # add your discus identifier

# # Tracker
# analytics: # Google Analytics

# # Build Settings
# markdown: kramdown
# plugins:
#   - jekyll-sitemap
#   - jekyll-paginate
#   - jemoji

# paginate: 8
# paginate_path: "/page/:num"

# exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

# Site Settings
title: "Hello, I'm Ryan Zhou"
description: "Product Manager & Software Developer with a passion for Web3&AI."
permalink: ":title/"
baseurl: ""  # Keep empty for GitHub Pages root
url: "https://ryanchou24.github.io"  # Your GitHub Pages URL
lang: "en"  # Default language

# Author Info
author:
  name: "Ryan Zhou"
  avatar: "/assets/img/ryan-avatar.jpg"  # Update with your actual avatar path
  bio: "Product Manager and Software Developer, passionate about AI-driven products and front-end development. Experienced in managing cross-functional teams, launching products, and designing user experiences."
  location: "Berkeley, CA"
  email: "ryanzhou@berkeley.edu"
  social:
    github: "Ryanchou24"
    linkedin: "zhongxing-zhou"
    twitter: "ryanchou24"
    facebook: ""

# Social Links
social:
  github: "https://github.com/Ryanchou24"
  linkedin: "https://www.linkedin.com/in/zhongxing-zhou/"
  twitter: "https://twitter.com/ryanchou24"

# SEO and Analytics
google_analytics: "YOUR_GOOGLE_ANALYTICS_TRACKING_ID"  # Add your Google Analytics tracking ID
sitemap:
  changefreq: "weekly"
  priority: 0.7
  exclude: 
    - "/404.html"

# Theme Settings
theme: minima  # Replace with your custom theme if using one

# Pagination
paginate: 5  # Number of posts per page
paginate_path: "/page/:num"

# Plugins
plugins:
  - jekyll-sitemap  # Generates sitemap.xml
  - jekyll-seo-tag  # Improves SEO with meta tags
  - jekyll-paginate  # Handles pagination
  - jemoji  # Adds emoji support
  - jekyll-feed  # Adds RSS feed support

# Markdown Settings
markdown: kramdown
kramdown:
  input: GFM  # GitHub-Flavored Markdown

# Exclude from Build
exclude:
  - "node_modules"
  - "gulpfile.js"
  - "package.json"
  - "yarn.lock"
  - "README.md"

# Professional Experience Section for the Home Page
professional_experience:
  - title: "AI Product Manager"
    company: "Stealth Startup (Led by Musical.ly's Founder)"
    location: "Shanghai, China"
    date: "Mar 2024 – Jul 2024"
    description: |
      Led product development for an AI messaging feature, improving retention by 2% through churn prediction modeling. Spearheaded efforts to reduce NSFW content by 50%, integrating a BERT model into the platform.
  - title: "Product Manager"
    company: "TikTok"
    location: "Shanghai, China"
    date: "Sep 2023 – Jan 2024"
    description: |
      Managed end-to-end product development for the TikTok Creator Academy, boosting click-through rates by 5%. Conducted user interviews to enhance creator satisfaction and improve traffic incentives.
  - title: "Technical Consultant"
    company: "FTI Consulting"
    location: "Shanghai, China"
    date: "May 2021 – Aug 2021"
    description: |
      Conducted forensic analysis and e-discovery for legal investigations, leveraging SQL and Nuix Discover to streamline reporting processes.

# Skills Section for the Home Page
skills:
  programming_languages:
    - "C++"
    - "Python"
    - "Java"
    - "JavaScript"
    - "SQL"
    - "SAS"
  tools:
    - "HTML"
    - "React"
    - "Git"
    - "AWS"
    - "Flask"
    - "MongoDB"
    - "Scikit-learn"
    - "PyTorch"
